<Project>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>Patrick JAILLET</Company>
    <Product>Sophia Script for Win11</Product>
    <Copyright>Copyright © 2026 Patrick JAILLET</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>0.9.0.0</Version>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

</Project>
